# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'AuthFirebaseApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AuthFirebaseApp

  pod 'Firebase/Core'
  pod 'Firebase/Auth'

  target 'AuthFirebaseAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'AuthFirebaseApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AuthFirebaseApp-tvOS

  target 'AuthFirebaseApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
